// <auto-generated />
namespace CaptainAmerica.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixingProyectoArchivoandArchivoComentariomodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingProyectoArchivoandArchivoComentariomodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201808210220570_Fixing ProyectoArchivo and ArchivoComentario models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
