// <auto-generated />
namespace CaptainAmerica.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version1001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version1001));
        
        string IMigrationMetadata.Id
        {
            get { return "201808130246357_Version 1.0.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
